-- CookClaw P0：分通道用户、长期记忆与用户画像
-- 制定日期：2026-07-23
-- 适用范围：Demo / 内测前最小数据地基
--
-- 设计约束：
-- 1. 暂不建立跨通道统一用户体系。
-- 2. 一个 channel + channel_account_id + channel_user_id 对应一条记录。
-- 3. PostgreSQL 保存长期记忆和聚合画像；短期会话状态由 Redis 保存。
-- 4. 不在本表保存通道 Token、密码、设备凭据或完整原始聊天记录。

BEGIN;

CREATE TABLE IF NOT EXISTS public.channel_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    channel VARCHAR(16) NOT NULL,
    channel_account_id VARCHAR(128) NOT NULL DEFAULT 'default',
    channel_user_id VARCHAR(255) NOT NULL,

    display_name VARCHAR(128),
    preferred_name VARCHAR(128),
    locale VARCHAR(16) NOT NULL DEFAULT 'zh-CN',

    profile JSONB NOT NULL DEFAULT
        '{
            "likes": [],
            "dislikes": [],
            "allergens": [],
            "dietary_constraints": [],
            "health_goals": [],
            "tags": []
        }'::jsonb,
    long_term_memory JSONB NOT NULL DEFAULT
        '{
            "facts": [],
            "summary": ""
        }'::jsonb,

    memory_version INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    last_seen_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_channel_users_identity
        UNIQUE (channel, channel_account_id, channel_user_id),
    CONSTRAINT ck_channel_users_channel
        CHECK (channel IN ('qq', 'weixin', 'whatsapp', 'web')),
    CONSTRAINT ck_channel_users_status
        CHECK (status IN ('active', 'disabled', 'deleted')),
    CONSTRAINT ck_channel_users_memory_version
        CHECK (memory_version >= 0),
    CONSTRAINT ck_channel_users_profile_object
        CHECK (jsonb_typeof(profile) = 'object'),
    CONSTRAINT ck_channel_users_memory_object
        CHECK (jsonb_typeof(long_term_memory) = 'object'),
    CONSTRAINT ck_channel_users_memory_facts
        CHECK (
            long_term_memory ? 'facts'
            AND jsonb_typeof(long_term_memory -> 'facts') = 'array'
        ),
    CONSTRAINT ck_channel_users_memory_summary
        CHECK (
            long_term_memory ? 'summary'
            AND jsonb_typeof(long_term_memory -> 'summary') = 'string'
        )
);

CREATE INDEX IF NOT EXISTS idx_channel_users_last_seen
    ON public.channel_users (last_seen_at DESC)
    WHERE status = 'active';

COMMENT ON TABLE public.channel_users IS
    'CookClaw P0 分通道用户表：保存长期记忆和聚合画像，暂不跨通道合并';
COMMENT ON COLUMN public.channel_users.channel IS
    '接入通道：qq、weixin、whatsapp、web';
COMMENT ON COLUMN public.channel_users.channel_account_id IS
    'CookClaw 通道账号；QQ/WhatsApp 单账号可用 default，微信多账号必须传 account_id';
COMMENT ON COLUMN public.channel_users.channel_user_id IS
    '用户在当前通道和通道账号下的平台标识';
COMMENT ON COLUMN public.channel_users.profile IS
    '当前有效聚合画像，供推荐读取；不作为记忆来源审计';
COMMENT ON COLUMN public.channel_users.long_term_memory IS
    '带来源、状态和时间信息的长期记忆 facts，以及压缩 summary';
COMMENT ON COLUMN public.channel_users.memory_version IS
    '长期记忆和画像更新的乐观锁版本';

COMMIT;
